apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-was
  namespace: was
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-was
  template:
    metadata:
      labels:
        app: petclinic-was
    spec:
      containers:
        - name: petclinic-was
          image:946775837287.dkr.ecr.ap-northeast-2.amazonaws.com/was-repo:v1.0.0-0d346b5
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
          env:
            - name: jdbc.url
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: jdbc.url
            - name: jdbc.username
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: jdbc.username
            - name: jdbc.password
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: jdbc.password

